export {default as Home} from './Home'
export {default as NavBar} from './NavBar'
export {default as Profile} from './Profile'
export {default as Messages} from './Messages'
export {default as Posts} from './Posts'
export {default as RegLog} from './RegLog'